### ISSUE TITLE
2 chỉ tiêu cùng 1 mẫu

### ISSUE THREAD

**Issue by vangnv80** [vinacert/lab#2]
![image_2020_10_18T01_24_45_742Z](https://user-images.githubusercontent.com/73054499/96361902-c4fffa80-1153-11eb-9ef6-b39e120ec1e8.png)

**Comment by vangnv80** [comment]
Số phiếu mấy vậy @tuananherp

**Comment by tuananherp** [comment]
SOP sản phẩm, Mã KH 7014 trong báo cáo KQTN:                                                                                           -	Một số sản phẩm chỉ BB giao mẫu chỉ giao As 1 lần nhưng Báo cáo KQTN As xuất hiện 02 lần
VD: các sản phẩm mã hóa mẫu 58744, 58737, 58739, 58742
-	Một số sản phẩm TCCS đã gắn QĐR và duyệt đạt nhưng báo cáo KQTN không liên kết mức yêu cầu TC/QC/QĐ  và không thể so sánh ở các chỉ tiêu Asen (As),  Cadimi (Cd), Chì (Pb) (các chỉ tiêu khác trong sản phẩm vẫn so sánh được) (VD: SP RB-BKC 80 TCCS 01:2019/RB-MT)
VD: SP RB-BKC 80, RB-MAXZIME, RB - VITA C, RB – PLATINUM..
-	Các sản phẩm xử lý môi trường có chứa các chất giao thêm (ngoài chỉ tiêu an toàn) vẫn chưa so sánh được ạ

**Comment by vangnv80** [comment]
![1](https://user-images.githubusercontent.com/73054499/96362849-93d6f880-115a-11eb-9856-43ff76ad5d58.PNG)
Sai ở TCCS bị double 2 mã ASen. Để anh xem bị gì rồi anh xóa

**Comment by vangnv80** [comment]
Phiếu kết quả anh chỉnh lại rồi
